export const questions = {
  1: { question: "What is the sum of all angles in a triangle?", answer: "180°" },
  2: { question: "A triangle with all sides equal is called?", answer: "Equilateral" },
  3: { question: "A triangle with one 90° angle is called?", answer: "Right" },
  4: { question: "Lines that never meet are called?", answer: "Parallel lines" },
  5: { question: "What is a line that has one endpoint called?", answer: "Ray" },
  6: { question: "How many sides does a decagon have?", answer: "10" },
  7: { question: "The longest chord of a circle is called?", answer: "Diameter" },
  8: { question: "A closed figure with four sides is called?", answer: "Quadrilateral" },
  9: { question: "An angle less than 90° is called?", answer: "Acute angle" },
  10: { question: "How many diagonals does a hexagon have?", answer: "9" },
  11: { question: "A polygon with all sides and angles equal is called?", answer: "Regular" },
  12: { question: "What do you call a line that touches a circle at one point?", answer: "Tangent" },
  13: { question: "What is the shape with only one curved surface?", answer: "Sphere" },
  14: { question: "The meeting point of two sides of a polygon is called?", answer: "Vertex" },
  15: { question: "What is the sum of interior angles of a quadrilateral?", answer: "360°" },
  16: { question: "How many edges does a cube have?", answer: "12" },
  17: { question: "The flat surface of a solid figure is called?", answer: "Face" },
  18: { question: "What is the shape of the base of a cylinder?", answer: "Circle" },
  19: { question: "A line that divides an angle into two equal parts is called?", answer: "bisector" },
  20: { question: "The point where medians of a triangle meet is called?", answer: "Centroid" },
  21: { question: "How many vertices does a rectangular prism have?", answer: "8" },
  22: { question: "A figure that can be folded into a solid is called?", answer: "Net" },
  23: { question: "The sum of all exterior angles of a polygon is always?", answer: "360°" },
  24: { question: "A parallelogram with all angles 90° is called?", answer: "Rectangle" },
  25: { question: "How many axes of symmetry does a circle have?", answer: "Infinite" },
  26: { question: "Which planet is known as the Red Planet?", answer: "Mars" },
  27: { question: "Who painted the Mona Lisa?", answer: "Leonardo da Vinci" },
  28: { question: "Which ocean is the largest on Earth?", answer: "Pacific" },
  29: { question: "Which country invented paper?", answer: "China" },
  30: { question: "What is the chemical symbol for gold?", answer: "Au" },
  31: { question: "Which city hosted the 2016 Summer Olympics?", answer: "Rio de Janeiro" },
  32: { question: "Which animal is the largest living mammal?", answer: "Blue whale" },
  33: { question: "Mount Everest lies on the border of Nepal and which country?", answer: "China" },
  34: { question: "What is the hardest natural substance on Earth?", answer: "Diamond" },
  35: { question: "Which continent has the most countries?", answer: "Africa" },
  36: { question: "Who discovered penicillin?", answer: "Alexander Fleming" },
  37: { question: "Which planet is closest to the Sun?", answer: "Mercury" },
  38: { question: "How many bones are there in the adult human body?", answer: "206" },
  39: { question: "What is the capital of Japan?", answer: "Tokyo" },
  40: { question: "Which metal is liquid at room temperature?", answer: "Mercury" },
  41: { question: "Who was the first person to walk on the Moon?", answer: "Neil Armstrong" },
  42: { question: "Which country is known as the Land of the Rising Sun?", answer: "Japan" },
  43: { question: "What is the smallest prime number?", answer: "2" },
  44: { question: "Which bird is known for its ability to mimic human speech?", answer: "Parrot" },
  45: { question: "Which ocean lies between Africa and Australia?", answer: "Indian Ocean" },
  46: { question: "Who wrote 'Romeo and Juliet'?", answer: "William Shakespeare" },
  47: { question: "What is the main gas found in the Earth's atmosphere?", answer: "Nitrogen" },
  48: { question: "Which organ in the human body pumps blood?", answer: "Heart" },
  49: { question: "What is the capital of Canada?", answer: "Ottawa" },
  50: { question: "Which instrument measures atmospheric pressure?", answer: "Barometer" },
};
